version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - "./mosquitto:/mosquitto"
    ports:
      - "8883:8883"
    expose:
      - 8883
    networks:
      - backend

  node-red:
    depends_on:
      - mosquitto
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Vilnius
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data:/data
    networks:
      - web-public
      - backend
    extra_hosts:
      - "slimcaddy.localhost=172.18.0.2"


networks:
  web-public:
    external: true
  backend:
    name: nodered-backend